USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_GIAODICHGOIRUT]    Script Date: 09/05/2024 22:59:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_GIAODICHGOIRUT]
@SOTK nvarchar(9), @LOAIGD nvarchar(2),  @SOTIEN money, @MANV nvarchar(10)
AS
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
BEGIN TRANSACTION 
BEGIN TRY 
	IF(@LOAIGD='GT')
	BEGIN
		IF EXISTS(SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.SOTK = @SOTK)
		BEGIN 
			UPDATE dbo.TaiKhoan
		    SET SODU = SODU + @SOTIEN
		    WHERE SOTK = @SOTK
		END
	END
	IF (@LOAIGD='RT')
	BEGIN
		IF EXISTS(SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.SOTK = @SOTK)
		BEGIN
			UPDATE dbo.TaiKhoan
			SET SODU = SODU - @SOTIEN
			WHERE SOTK = @SOTK
		END
	END
	IF EXISTS(SELECT NV.MANV FROM NhanVien NV WHERE NV.MANV = @MANV)
	BEGIN 
		INSERT INTO dbo.GD_GOIRUT(SOTK,LOAIGD,NGAYGD,SOTIEN,MANV)
		VALUES(@SOTK, @LOAIGD, GETDATE(), @SOTIEN, @MANV)
	END
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF(@@TRANCOUNT > 0)
	BEGIN 
		ROLLBACK TRANSACTION
		RAISERROR('Lỗi khi gởi rút tiền. Vui lòng kiểm tra!', 16 ,1)
	END
END CATCH

GO

