USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_GIAODICHCHUYENTIEN]    Script Date: 09/05/2024 22:59:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_GIAODICHCHUYENTIEN]
    @SOTK_CHUYEN nvarchar(9),
    @SOTK_NHAN nvarchar(9),
    @SOTIEN MONEY,
    @MANV nchar(10)
AS
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
BEGIN TRANSACTION
BEGIN TRY
    IF EXISTS (SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.SOTK = @SOTK_CHUYEN)
    BEGIN
        UPDATE dbo.TaiKhoan
        SET SODU = SODU - @SOTIEN
        WHERE SOTK = @SOTK_CHUYEN
    END
    IF EXISTS (SELECT TK.SOTK FROM TaiKhoan TK WHERE TK.SOTK = @SOTK_NHAN)
    BEGIN
        UPDATE dbo.TaiKhoan
        SET SODU = SODU + @SOTIEN
        WHERE SOTK = @SOTK_NHAN
    END
    IF EXISTS (SELECT NV.MANV FROM NhanVien NV WHERE NV.MANV = @MANV)
    BEGIN
        INSERT INTO dbo.GD_CHUYENTIEN (SOTK_CHUYEN, NGAYGD, SOTIEN, SOTK_NHAN, MANV)
        VALUES (@SOTK_CHUYEN, GETDATE(), @SOTIEN, @SOTK_NHAN, @MANV)
    END
    COMMIT TRANSACTION
END TRY
BEGIN CATCH
    IF (@@TRANCOUNT > 0)
    BEGIN
        ROLLBACK TRANSACTION
        RAISERROR('Lỗi khi chuyển tiền. Vui lòng kiểm tra!', 16, 1)
    END
END CATCH


GO

