USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIEMTRACMNDNV]    Script Date: 09/05/2024 22:59:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_KIEMTRACMNDNV]
@CMND nchar(10)
AS
BEGIN
	IF EXISTS (SELECT NV.CMND FROM NHANVIEN NV WHERE NV.CMND = @CMND)
		RETURN 1
	IF EXISTS (SELECT NV.CMND FROM LINK1.NGANHANG.DBO.NHANVIEN NV WHERE NV.CMND = @CMND)
		RETURN 1
	RETURN 0
END



GO

