USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIEMTRACMNDKH]    Script Date: 09/05/2024 22:59:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_KIEMTRACMNDKH]
@CMND nchar(10)
AS
BEGIN
	IF EXISTS (SELECT KH.CMND FROM KhachHang KH WHERE KH.CMND = @CMND)
		RETURN 1
	IF EXISTS (SELECT KH.CMND FROM LINK1.NGANHANG.DBO.KhachHang KH WHERE KH.CMND = @CMND)
		RETURN 1
	RETURN 0
END



GO

