CREATE PROC [dbo].[SP_KIEMTRAMANHANVIEN]
	@MANV NCHAR(10)
AS 
BEGIN
	IF EXISTS (SELECT NV.MANV FROM NhanVien NV WHERE NV.MANV = @MANV)
		RETURN 1
    IF EXISTS (SELECT NV.MANV FROM LINK0.NGANHANG.DBO.NhanVien NV WHERE NV.MANV = @MANV)
		RETURN 1
	RETURN 0
END
