USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIEMTRAMANHANVIEN]    Script Date: 09/05/2024 23:00:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[SP_KIEMTRAMANHANVIEN]
	@MANV NVARCHAR(10)
AS 
BEGIN
	IF EXISTS (SELECT NV.MANV FROM NhanVien NV WHERE NV.MANV = @MANV)
		RETURN 1
    IF EXISTS (SELECT NV.MANV FROM LINK0.NGANHANG.DBO.NhanVien NV WHERE NV.MANV = @MANV)
		RETURN 1
	RETURN 0
END



GO

