USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_KHACHHANGDANGNHAP]    Script Date: 09/05/2024 22:59:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_KHACHHANGDANGNHAP]
@CMND nchar(10)
AS
BEGIN
	SELECT CMND, HOTEN  = HO +' ' + TEN 
	FROM KhachHang
	WHERE CMND = @CMND
END


GO

