USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_KIEMTRASDT]    Script Date: 09/05/2024 23:00:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_KIEMTRASDT]
@SODT NVARCHAR(15)
AS
BEGIN
	IF EXISTS (SELECT NV.SODT FROM NhanVien NV WHERE NV.SODT = @SODT)
		RETURN 1
	IF EXISTS (SELECT NV.SODT FROM LINK0.NGANHANG.DBO.NhanVien NV WHERE NV.SODT = @SODT)
		RETURN 1
	IF EXISTS (SELECT KH.SODT FROM KhachHang KH WHERE KH.SODT = @SODT)
		RETURN 1
	IF EXISTS (SELECT KH.SODT FROM LINK0.NGANHANG.DBO.KhachHang KH WHERE KH.SODT = @SODT)
		RETURN 1
	RETURN 0
END 


GO

