USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_LIETKEKHACHHANGTHEOCHINHANH]    Script Date: 09/05/2024 23:00:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_LIETKEKHACHHANGTHEOCHINHANH]
AS
BEGIN
	SELECT HO, TEN, DIACHI, PHAI, CMND, NGAYCAP, SODT
	FROM KhachHang
END

GO

