USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_LAYSTKKHACHHANG]    Script Date: 27/06/2024 15:16:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_LAYSTKKHACHHANG] 
@CMND NVARCHAR(10)
AS
BEGIN
	SELECT SOTK FROM LINK0.NGANHANG.DBO.TAIKHOAN 
	WHERE TAIKHOAN.CMND = @CMND
END
GO

