USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_LIETKETAIKHOANMOTRONG1THOIGIAN]    Script Date: 13/05/2024 14:36:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[sp_LIETKETAIKHOANMOTRONG1THOIGIAN]
	@MACN nvarchar(10),
	@NGAYBD DATETIME,
	@NGAYKT DATETIME	
AS
BEGIN
	IF @MACN = 'HAICN'
		BEGIN
			SELECT SOTK, CMND, SODU, MACN, NGAYMOTK
			FROM TaiKhoan
			WHERE NGAYMOTK BETWEEN @NGAYBD AND @NGAYKT
		END
	ELSE
		BEGIN
			SELECT SOTK, CMND, SODU, MACN, NGAYMOTK
			FROM TaiKhoan
			WHERE (NGAYMOTK BETWEEN @NGAYBD AND @NGAYKT) AND (MACN = @MACN)
		END
END
GO

