USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SAOKEGIAODICHCUA1TAIKHOANTRONG1KHOANGTHOIGIAN]    Script Date: 27/06/2024 10:29:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SAOKEGIAODICHCUA1TAIKHOANTRONG1KHOANGTHOIGIAN]
	@SOTK nvarchar(9), 
	@NGAYBD DATETIME,
	@NGAYKT DATETIME
AS
	DECLARE @SOTIENBANDAU MONEY
	DECLARE @SODU MONEY
	DECLARE @tab table(SODUDAU MONEY, NGAYGD DATETIME, LOAIGD nvarchar(2), SOTIEN MONEY, SODUSAU MONEY)
	DECLARE @tabGD table(NGAYGD DATETIME, LOAIGD nvarchar(2), SOTIEN MONEY, SOTK nvarchar(9))

	SELECT @SODU = SODU FROM TaiKhoan TK WHERE TK.SOTK = @SOTK

	SELECT @SOTIENBANDAU = @SODU + SUM(CASE WHEN GD.LOAIGD = 'RT' THEN GD.SOTIEN WHEN GD.LOAIGD = 'GT' THEN -GD.SOTIEN 
	WHEN GD.SOTK = @SOTK THEN -GD.SOTIEN ELSE GD.SOTIEN END)
	FROM (SELECT NGAYGD, SOTIEN, LOAIGD='CT', SOTK = CT.SOTK_NHAN  FROM LINK0.NGANHANG.DBO.GD_CHUYENTIEN CT WHERE CT.SOTK_NHAN = @SOTK OR CT.SOTK_CHUYEN = @SOTK
	UNION SELECT NGAYGD, SOTIEN, LOAIGD, SOTK FROM LINK0.NGANHANG.DBO.GD_GOIRUT WHERE GD_GOIRUT.SOTK = @SOTK) GD
	WHERE GD.NGAYGD >= @NGAYBD
 
	DECLARE @SODUDAU MONEY, @NGAYGD DATETIME, @LOAIGD NVARCHAR(2), @SOTIEN MONEY, @SODUSAU MONEY, @TK_NHAN NVARCHAR(9), @TEMP MONEY
	DECLARE cursorTK CURSOR 
	FOR SELECT GD.NGAYGD, GD.LOAIGD, GD.SOTIEN, GD.SOTK
	FROM (SELECT NGAYGD, SOTIEN, LOAIGD='CT', SOTK = CT.SOTK_NHAN  FROM LINK0.NGANHANG.DBO.GD_CHUYENTIEN CT WHERE CT.SOTK_NHAN = @SOTK OR CT.SOTK_CHUYEN = @SOTK
	UNION SELECT NGAYGD, SOTIEN, LOAIGD, SOTK FROM LINK0.NGANHANG.DBO.GD_GOIRUT WHERE GD_GOIRUT.SOTK = @SOTK) GD
	Where GD.NGAYGD BETWEEN @NGAYBD AND @NGAYKT
	ORDER BY GD.NGAYGD


	OPEN cursorTK
	FETCH NEXT FROM cursorTK
		INTO @NGAYGD, @LOAIGD, @SOTIEN, @TK_NHAN
	SET @SODUDAU = @SOTIENBANDAU
	IF(@LOAIGD = 'RT')
				SET @SODUSAU = @SODUDAU - @SOTIEN
		ELSE IF(@LOAIGD = 'GT')
				SET @SODUSAU = @SODUDAU + @SOTIEN
		ELSE IF(@TK_NHAN = @SOTK)
				SET @SODUSAU = @SODUDAU + @SOTIEN
		ELSE
				SET @SODUSAU = @SODUDAU - @SOTIEN
	WHILE @@FETCH_STATUS = 0
	BEGIN 
		SET @TEMP = @SODUSAU   
		INSERT INTO @tab(SODUDAU, NGAYGD, LOAIGD, SOTIEN, SODUSAU)
		VALUES (@SODUDAU, @NGAYGD, @LOAIGD, @SOTIEN, @SODUSAU) 
		FETCH NEXT FROM cursorTK
			INTO @NGAYGD, @LOAIGD, @SOTIEN, @TK_NHAN
	
		SET @SODUDAU = @TEMP
		IF(@LOAIGD = 'RT')
				SET @SODUSAU = @TEMP - @SOTIEN
		ELSE IF(@LOAIGD = 'GT')
				SET @SODUSAU = @TEMP + @SOTIEN
		ELSE IF(@TK_NHAN = @SOTK)
				SET @SODUSAU = @TEMP + @SOTIEN
		ELSE
				SET @SODUSAU = @TEMP - @SOTIEN
END
SELECT SODUDAU, NGAYGD,(CASE WHEN (LOAIGD = 'CT' AND SODUSAU < SODUDAU) THEN N'CHUYỂN TIỀN' WHEN (LOAIGD = 'CT' AND SODUSAU > SODUDAU) THEN N'NHẬN TIỀN' WHEN LOAIGD = 'GT' THEN N'GỞI TIỀN' ELSE N'RÚT TIỀN' END) AS LOAIGD, SOTIEN, SODUSAU
FROM @tab t
CLOSE cursorTK  
DEALLOCATE cursorTK 

GO

